name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branhces: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Installing NodeJS
      uses: actions/setup-node@v5
      with:
         node-version: '15.x'

